# Site settings
# in the templates available like {{ site.myvariable }}.
title: Roy Schreuder
brand: Roy Schreuder
headline: Graffiti artist
description: > # this means to ignore newlines until "baseurl:"
  Portfolio website of Leeuwarden's Roy Schreuder
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://royschreuder.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

include: ['_pages']

# Build settings
markdown: kramdown

# Contacts
email: roy@royschreuder.com
phone: +31 6 40604409

# Tracking
googleAnalitycsID: UA-xxxxxx

sass:
    sass_dir: _sass
    style: compressed

collections_dir: collections

