# config.yml

backend:
  name: github # Or gitlab
  repo: martijnvdbrug/royschreuder.com # Your username and repository
  branch: master # Branch to use
  base_url: https://europe-west1-cable-cms.cloudfunctions.net/authHandler # The base URL for your Firebase Function
  auth_endpoint: /auth # The path to the OAuth endpoint of the function

media_folder: 'web-dist/images/portfolio'
collections:
  - label: "Teksten"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "About"
        name: "about"
        file: "_data/en.yml"
        fields:
          - {label: Title, name: about_title, widget: string}
          - {label: Content, name: about_content, widget: text}
      - label: "Over mij"
        name: "over mij"
        file: "_data/nl.yml"
        fields:
          - {label: Title, name: about_title, widget: string}
          - {label: Content, name: about_content, widget: text}
  - label: "Portfolio"
    name: "portfolio"
    editor:
      preview: false
    files:
      - label: "Portfolio afbeeldingen"
        name: "afbeeldingen"
        file: "_data/portfolio.yml"
        fields:
          - label: Afbeeldingen
            name: images
            widget: list
            fields:
              - {label: Afbeelding, name: url, widget: image}
              - {label: Beschrijving, name: description, widget: string}
              - {label: Categorie 1, name: tag1, widget: string, pattern: ["^($|stencil|freehand|workshop|shop)$", "Moet een van de volgende categorien zijn: stencil, freehand, workshop of shop"]}
              - {label: Categorie 2, name: tag2, widget: string, pattern: ["^($|stencil|freehand|workshop|shop)$", "Moet een van de volgende categorien zijn: stencil, freehand, workshop of shop"]}
