# config.yml

backend:
  name: github # Or gitlab
  repo: martijnvdbrug/royschreuder.com # Your username and repository
  branch: master # Branch to use
  base_url: https://europe-west1-cable-cms.cloudfunctions.net/authHandler # The base URL for your Firebase Function
  auth_endpoint: /auth # The path to the OAuth endpoint of the function

media_folder: 'web-dist/images/'
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "_data/en.yml"
        fields:
          - {label: Title, name: about_title, widget: string}
          - {label: Content, name: about_content, widget: string}
      - label: "Over mij"
        name: "over mij"
        file: "_data/nl.yml"
        fields:
          - {label: Title, name: about_title, widget: string}
          - {label: Content, name: about_content, widget: string}
  - label: "Portfolio"
    name: "portfolio"
    files:
      - label: "Freehand"
        name: "freehand"
        file: "_data/freehand.yml"
        fields:
          - {label: Title, name: url, widget: string}
          - {label: Content, name: title, widget: string}
          - {label: Description, name: description, widget: string}
      - label: "Stencil"
        name: "stencil"
        file: "_data/stencils.yml"
        fields:
          - {label: Title, name: url, widget: string}
          - {label: Content, name: title, widget: string}
          - {label: Description, name: description, widget: string}
      - label: "Workshop"
        name: "workshop"
        file: "_data/workshop.yml"
        fields:
          - {label: Title, name: url, widget: string}
          - {label: Content, name: title, widget: string}
          - {label: Description, name: description, widget: string}
      - label: "Shop"
        name: "shop"
        file: "_data/shop.yml"
        fields:
          - {label: Title, name: url, widget: string}
          - {label: Content, name: title, widget: string}
          - {label: Description, name: description, widget: string}
